tunnel:
  mtu: 1280
  ipv4: 10.0.0.2

socks5:
  port: 1080
  address: 127.0.0.1
  udp: 'tcp'

misc:
  log-file: stderr
  log-level: warn
  task-stack-size: 32768
  connect-timeout: 8000
  read-write-timeout: 60000
  tcp-buffer-size: 65536
  udp-recv-buffer-size: 65536