tunnel:
  mtu: 1280
  ipv4: 10.0.0.2
  ipv6: '::'

socks5:
  port: 1080
  address: 127.0.0.1
  # UDP ผ่าน TCP ไป SOCKS5 → แอปจะใช้ UDP ASSOCIATE แล้วส่งต่อ udpgw
  udp: 'udp'

misc:
  log-file: stderr
  log-level: warn
  task-stack-size: 65536
  connect-timeout: 15000
  read-write-timeout: 300000
  tcp-buffer-size: 131072
  udp-recv-buffer-size: 65536
  limit-nofile: 65535
